### ISSUE TITLE
Can't reorientate logos for titles using assets generated from Steam ROM Manager (potentially more)

### ISSUE THREAD

**Issue by CarJem** [SteamGridDB/decky-steamgriddb#39] opened 2023-02-22 21:49 UTC
**Steps to reproduce:**
1. Add game via Steam ROM Manager with Logo
2. Use Plugin to move the Logo
3. The loading symbol appears until pressing the d-pad, then, it's taking up the whole space and is not orientable.

**Images Used + Shortcuts.vdf**
- Using the Game titled "Bionicle Heroes"
[TestData.zip](https://github.com/SteamGridDB/decky-steamgriddb/files/10808599/TestData.zip)

**Comment by doZennn** [comment] 2023-02-28 06:07
Can't reproduce but possibly fixed in https://github.com/SteamGridDB/decky-steamgriddb/commit/c461243f985f27ecaf99a843902c58bccc4abc24

**Comment by CarJem** [comment] 2023-03-08 20:13
It now actually functions, however still does not update It's position unless you update it manually.

**Comment by doZennn** [comment] 2023-03-08 20:18
Can you elaborate?

**Comment by CarJem** [comment] 2023-03-10 14:15
basically... The initial state of the logo will be blown up to maximum size until you adjust its size

**Comment by doZennn** [comment] 2023-08-24 02:10
Still can't reproduce this, and had no other reports. Closing but feel free to reopen if you can give me reproducible steps.

**Closed** 2023-08-24 02:10 UTC
Labels: bug
